### ISSUE TITLE
Factorio 0.17.23 disabled the mod as incompatible with the game

### ISSUE THREAD

**Issue by garrotte** [renoth/factorio-alien-module#25]
1.326 Loading mod alien-module 0.6.4 (data.lua)
   1.329 Error ModManager.cpp:1294: Failed to load mod "alien-module": __alien-module__/data.lua:13: __alien-module__/prototypes/technology/technology.lua:69: attempt to index field 'electric-energy-accumulators-1' (a nil value)
stack traceback:
	__alien-module__/prototypes/technology/technology.lua:69: in main chunk
	[C]: in function 'require'
	__alien-module__/data.lua:13: in main chunk
stack traceback:
	[C]: in function 'require'
	__alien-module__/data.lua:13: in main chunk

**Comment by ChildishGiant** [comment]
Yep, both my friend and I when launching into .17.23, were told to disable the mod

**Comment by krlsmnk** [comment]
Yep. Same deal here. Came from the mod page cuz it told me to post here. Verbatim error.

**Comment by Glendening** [comment]
Is the error due 17.23 changing the name of electric-energy-accumulators-1 to electric-energy-accumulators ?
More than a few mods have broken due to this change so I assume the cause might be the same here.

**Comment by krlsmnk** [comment]
That sounds right. I had an accumulator mod break with a similar error. 

Sent from Yahoo Mail on Android 
 
  On Fri, Mar 29, 2019 at 7:37 PM, Glendening<notifications@github.com> wrote:   
Is the error due 17.23 changing the name of electric-energy-accumulators-1 to electric-energy-accumulators ?
More than a few mods have broken due to this change so I assume the cause might be the same here.

**Comment by ChildishGiant** [comment]
I think it's probably a combination of that and these two other changes.

- The game now checks that technology levels are contiguous.
- Non-upgrade technologies are now considered to be level 1; previously they were level 0.
