### ISSUE TITLE
Hang on hypermodule upgrade

### ISSUE THREAD

**Issue by ChildishGiant** [renoth/factorio-alien-module#31]
My friend and I are late game (34 hours into the save) and when we upgraded hypermodules from level 23 to 24 the game froze for a few seconds. Maybe it should be made async?

https://gfycat.com/SereneEasygoingDeinonychus

**Comment by renoth** [comment]
This is known and somewhat intentional.
While that would be good, i dont see a way to make this function async since all players would have to have the same state at any given moment. For example one player cannot have another module level in a factory than another, the game states would diverge / desynchronize.
If you find a way you could propose a Pull Request.

**Comment by unhott** [comment]
I don't have time to try scripting it out right now, but I want to get some thoughts down here in case I forget about it and someone else wants to give it a shot. We could try looping over each game surface in the background, but spread out over the chunks using surface.get_chunks(). Instead of searching the entire surface on level-up you just search a chunk every second or so, constantly. This would mean that the upgrades wouldn't be instantaneous, but they would catch all things ( eventually -- provided they settle somewhere). 

https://lua-api.factorio.com/latest/LuaChunkIterator.html

Create a dictionary in the global table, where the key is the surface.index and 
set each value to a chunk iterator for that surface. ( surface.get_chunks() ). Then, on nth tick, do chunkIterator.operator(). When you hit nil, restart from the beginning. I would try 60 ticks to start, and maybe go to 300 if it is slowing down the game. 

https://lua-api.factorio.com/latest/LuaChunkIterator.html#LuaChunkIterator.operator%20()

This should keep all of the games sync'd.
