### ISSUE TITLE
issue from #59 still not fixed

### ISSUE THREAD

**Issue by ResidentOfKill** [renoth/factorio-alien-module#62]
![adwwdasd](https://user-images.githubusercontent.com/66139191/94350215-75df1200-004c-11eb-8769-2eee524ee8e1.PNG)
 Here´s the proof

**Comment by renoth** [comment]
Thanks for the info, i reverted some code and will deal with the issue later

**Comment by renoth** [comment]
Please test with 1.1.4 if it works

**Comment by HEROgold** [comment]
Same issue for me, this happend on 1.01 with more then 10K modules to upgrade.
a freeze spike happened at 5K or above, this is due to the game trying to replace all modules at once in a single tick.
But it doesnt crash anymore in 1.04, the freeezing spike is still here, maybe there is a workaround where you try to find lower levels then current and upgrade only 200 at maximum each tick. But no crash anymore!

**Comment by ResidentOfKill** [comment]
@renoth Works fine now in the 1.1.4
