### ISSUE TITLE
If you have a hypermodule in a filtered hotbar slot while the level increases, those modules won't level up.

### ISSUE THREAD

**Issue by ChildishGiant** [renoth/factorio-alien-module#7]

**Comment by renoth** [comment]
Interesting, i thought the hotbar was just a view on the inventory. So you have a hypermodule in the inventory and it is linked to your hotbar, the module does not increase in level?

**Comment by ChildishGiant** [comment]
In my playthrough with a friend he's had a few not level up with the rest and they seem to be the ones in his hotbar that have the blue filter on. This'll probably be because that only lets that specific item in that slot and the levels are technically two different items.
![image](https://user-images.githubusercontent.com/13716824/42950880-de4e3ae8-8b6c-11e8-9db2-046647ec41c4.png)

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/43047706-5599958a-8dd3-11e8-8656-c45d1e555063.png)
I can confirm this is why. I've had one module in a filtered slot to check and when we went from 29 to 30 it didn't level up.

**Comment by ChildishGiant** [comment]
https://gfycat.com/gifs/detail/UntriedAdolescentAndeancondor Here is a video of us leveling up from 31 to 32 and you can see that the level 30 didn't level up.

**Comment by renoth** [comment]
Thanks for the video, i am not sure as to why the problem occurs but one possibility is the following:
Since your inventory is very large (more than 100 slots) it is possible that these modules are not found by the inventory loop (finding only the first 100 slots). One possibility to verify this would be to place them in a chest and see what happens. In the meantime i will increase the number of player inventory slots to search.

**Comment by renoth** [comment]
I published version 0.4.4, please test and report the findings

**Comment by renoth** [comment]
Since there has been no feedback, i close the issue
